In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\Github\Datasets\news.csv')
print(df.shape)
df.head()

(6335, 4)


Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [3]:
#define label and feature
x = df.text
y = df.label

## TF-IDF Vectorizer
<img src ='images\tfidf.jpg'>

In [4]:
#build vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english',max_df=0.7)
#fit and transform train and test feature
x = tfidf_vectorizer.fit_transform(x)

In [5]:
#train test splitting
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2, random_state=5)

## Build Model Using Logistic Regression Algorithm

In [8]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(ytest,lr.predict(xtest))

0.9218626677190213

## Build Model using Passive Aggressive Classifier
<img src ='images\pasagg.jpg'>

In [6]:
#passive aggresive classifier
from sklearn.linear_model import PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(xtrain,ytrain)

PassiveAggressiveClassifier(C=1.0, average=False, class_weight=None,
                            early_stopping=False, fit_intercept=True,
                            loss='hinge', max_iter=50, n_iter_no_change=5,
                            n_jobs=None, random_state=None, shuffle=True,
                            tol=0.001, validation_fraction=0.1, verbose=0,
                            warm_start=False)

In [7]:
accuracy_score(ytest,pac.predict(xtest))

0.9455406471981057

## Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf = RandomForestClassifier(n_estimators=35,max_depth=20,min_samples_leaf=40,min_samples_split=50,
                                random_state=5,oob_score=True)
rf.fit(xtrain,ytrain)
accuracy_score(ytest,rf.predict(xtest))

0.8121546961325967

In [11]:
#Build confusion matrix
print('Confusion Matrix Passive Aggresive Classifier')
confusion_matrix(ytest,pac.predict(xtest))

Confusion Matrix Passive Aggresive Classifier


array([[604,  33],
       [ 36, 594]], dtype=int64)

In [21]:
a = 604
b = 604+36
print('ROC: ',a/b)

ROC:  0.94375


In [12]:
#Build confusion matrix
print('Confusion Matrix Logistic Regression')
confusion_matrix(ytest,lr.predict(xtest))

Confusion Matrix Logistic Regression


array([[603,  34],
       [ 65, 565]], dtype=int64)

In [22]:
a = 603
b = 603+65
print('ROC: ',a/b)

ROC:  0.9026946107784432


In [19]:
#Build confusion matrix
print('Confusion Matrix Random Forest')
confusion_matrix(ytest,rf.predict(xtest))

Confusion Matrix Random Forest


array([[535, 102],
       [136, 494]], dtype=int64)

## Conclusion
Based on cross validation on confusion matrix, Passive Aggresive Classifier should be the best model to this data. 